version: '3'

services:
  kong:
    image: kong:2.1
    container_name: kong
    depends_on:
      - postgres
    networks:
      - kong-net
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - "KONG_DATABASE=postgres" 
      - "KONG_PG_HOST=kong-database" 
      - "KONG_PG_PASSWORD=kong"
      - "KONG_CASSANDRA_CONTACT_POINTS=kong-database" 
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout" 
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout" 
      - "KONG_PROXY_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr" 
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" 

  kong-migrations:
    image: kong:2.1
    container_name: kong-migrations
    command: "kong migrations bootstrap"
    depends_on:
      - postgres
    networks:
      - kong-net
    environment:
      - "KONG_DATABASE=postgres" 
      - "KONG_PG_HOST=kong-database" 
      - "KONG_PG_PASSWORD=kong"
      - "KONG_PG_PORT=5432"

  postgres:
    image: postgres:11
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_PASSWORD=kong"
      - "POSTGRES_DB=kong"

  konga:
    image: pantsel/konga:latest
    container_name: konga
    depends_on:
      - kong
    networks:
      - kong-net
    ports:
      - 1337:1337
    environment:
      - "NODE_ENV=production"
      - "TOKEN_SECRET="


networks:
  kong-net:
    
